# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - vqv/ggbiplot
  
before_install:
  - sudo $(which R) CMD javareconf
  
notifications:
  email:
    on_success: enrique.audain@gmail.com
    on_failure: enrique.audain@gmail.com
